### ISSUE TITLE
Adhere to the StatsModels.jl API

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/KrigingEstimators.jl#1]
In order to generalize the estimators further, we need to adhere to the StatsModels.jl API. This issue is a reminder to myself, I will fix it at some point in the future.

**Comment by jpfairbanks** [comment]
This package looks really cool. I had a question about the API,

You define `estimate(estimator::KrigingEstimator, xₒ::AbstractVector)`, but you could use a `call` or `getindex` API. `estimator(x::AbstractVector)` or `estimator[x]` make sense. I've been spending some time with DifferentialEquations.jl lately, so these apis look more natural to me. Is there are reason to go with StatsModels API rather than built in julia api like `call` or `getindex`? 

Also, I read `estimate` differently so I thought it was the verb (es-ti-MATE) "to construct an estimator" rather than  the noun (est-i-mitt) "value of the estimator at the location". Good thing the type annotations let me figure out the correct reading by static analysis, 😉.

**Comment by juliohm** [comment]
Thanks @jpfairbanks! Didn't know you were into Kriging stuff as well :slightly_smiling_face: 

The idea with StatsModels.jl is that we can generalize the interface to handle multivariate problems. Let's say co-estimate two variables exploiting the correlation between them. The formula syntax from StatsModels.jl would allow us to formulate these types of problems (I hope).

I feel that `getindex` or `call` with estimator objects is not intuitive, maybe a little abuse of syntax? I like the idea of renaming the function `estimate` to `evaluate` though. I see now how it sounds weird.

**Comment by juliohm** [comment]
I will think about it more carefully, maybe the `call` syntax is intuitive :+1: :)

**Comment by jpfairbanks** [comment]
> Thanks @jpfairbanks! Didn't know you were into Kriging stuff as well 🙂

 Haha, I am not, I just wanted to see what you've been up to.

It took 3 minutes of thinking to come around on `call`? My understanding is that Kriging builds something like a KDE over the input space, you give it sample data from `X x Y` and it returns a "function" from `X -> (Y,Y^2)`. Where the the values of the function are (mean, variance) estimates.  

I've been thinking about how we encode semantics of scientific models into Julia code lately. The propagation of `Unitful.jl` units and interfaces like `DifferentialEquations.jl` are interesting.

**Comment by juliohm** [comment]
Nice, thanks for sharing the thoughts, definitely welcome :ok_hand: . I will work on a PR to make the API clearer. I will also check again the current status of StatsModels.jl, which was not ready by the time I opened this issue.

**Comment by juliohm** [comment]
I've renamed the function `estimate` to `predict` on the master branch. It is a clearer name and follows other ML packages' conventions. :+1:
